[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"
